version: '2.0'
services:
  tensorflow:
    build:
      context: ./tensorflow
    image: tensorflow/test_resnet
    command: --model_config_file=/config/config.conf
    container_name: tfserving_resnet
    ports:
      - "8501:8501"
    environment:
      - MODEL_NAME=resnet
    
   