FROM emacski/tensorflow-serving:1.14.0-linux_arm_armv7-a_neon_vfpv4
COPY . ./
COPY ./tensorflow/tmp/mobilenet_v2_100_224 /models/mobilenet_v2_100_224

COPY ./config.conf /config/config.conf

ENV MODEL_CONFIG_FILE=/config/config.conf