FROM emacski/tensorflow-serving:1.14.0-linux_arm_armv7-a_neon_vfpv3
COPY . ./
COPY ./tmp/{{model-name}} /models/{{model-name}}

COPY ./config.conf /config/config.conf

ENV MODEL_CONFIG_FILE=/config/config.conf